version: '3.8'

services:

  backend:
    build: ./social_app_backend/social_app
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./social_app_backend/social_app:/usr/src/social_app_backend/social_app
    ports:
      - 8000:8000

  frontend:
    build: ./social_app_frontend
    command: npm start
    volumes:
      - /app
      - /app/node_modules
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true