version: '3.8'

services:

  backend:
    build: ./social_app_backend/social_app
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./social_app_backend/social_app:/usr/src/social_app_backend/social_app
    ports:
      - 8000:8000
    env_file:
      - ./social_app_backend/social_app/.env.dev
    depends_on:
      - db

  db:
    image: postgres:13.0-alpine
    container_name: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${USER}
      - POSTGRES_PASSWORD=${PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=${EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PASSWORD}
      - PGADMIN_LISTEN_PORT=5050
    ports:
      - "5050:5050"

  frontend:
    build: ./social_app_frontend
    command: npm start
    volumes:
      - ./social_app_frontend:/app
      - /app/node_modules
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true

volumes:
  postgres_data: